doc/source/tutorials/data
notebooks/tutorials/beginner_workflow/workflow.ipynb
openghg/modules/_gcwerks.py
requirements-dev.txt

Minor edits:
- There was a typo in the tutorial requirements-dev file.
- I think you need a link to the AGAGE data folder for the workflow notebook to compile when making docs, which I've added. 
- Added some more info in one of the GCWERKS processing error messages

Fixing some minor typos and path issues in tutorial branch

---

doc/source/install.rst
openghg/data/attributes.json
openghg/modules/_gcwerks.py
openghg/processing/_attributes.py

Two small fixes for the errors with processing capegrim and barbados files

Fixes for processing of capegrim and barbados GCWERKS files

---

openghg/dataobjects/__init__.py
openghg/dataobjects/_basedata.py
openghg/dataobjects/_footprint_data.py
openghg/dataobjects/_obsdata.py
openghg/localclient/__init__.py
openghg/localclient/_get_observations.py
openghg/localclient/_search.py
openghg/modules/_crds.py
openghg/modules/_datasource.py
openghg/processing/__init__.py
openghg/processing/_attributes.py
openghg/processing/_observations.py
openghg/processing/_process_footprint.py
openghg/processing/_recombination.py
openghg/processing/_search.py
openghg/processing/_segment.py
openghg/util/_util.py
requirements.txt

This gets the OpenGHG version of `get_obs` (called `get_observations` in OpenGHG) up to the point of the `get_single_site`. To get to the full `get_obs` stage we need to work on how we're going to create a nicer search interface.

Get obs refactor

---

openghg/modules/__init__.py
openghg/modules/_datasource.py
openghg/modules/_emissions.py
openghg/processing/_process_footprint.py
openghg/processing/_segment.py

This adds a basic `Emissions` class that reads in an emissions NetCDF and stores it. Further work needs doing on the metadata that's read and how the emissions data (if large) is stored.

Added very basic read of emissions data

---

.github/workflows/main.yaml

Adding in tests with Python 3.9

Adding Python 3.9 GitHub actions runner

---

openghg/data/attributes.json
openghg/modules/_btt.py
tests/modules/test_btt.py

Default sampling period has been added for BTT module.
Links to Issue #71.

Updating default sampling period for BTT module

---

doc/source/development/fn_setup.rst
openghg/client/_retrieve.py
openghg/data/acrg_site_info.json
openghg/data/process_gcwerks_parameters.json
openghg/data/process_gcwerks_parameters_bp1.json
openghg/modules/_crds.py
openghg/util/_export.py
requirements-dev.txt
requirements-server.txt
requirements.txt
tests/localclient/test_get_surface_obs.py
tests/modules/test_crds.py
tests/modules/test_datasource.py
tests/processing/test_attributes.py
tests/processing/test_search.py
tests/services/test_retrieve.py
tests/services/test_searchfn.py
tests/util/test_export.py

Adds in some metadata so the CRDS module can process data from the instrument at Killearn Village Hall for COP26.

Small changes for KVH CRDS processing

---

requirements-server.txt

Adding uvloop back for Fn speedup.

Readding uvloop

---

.github/workflows/main.yaml
README.md
requirements-dev.txt
tests/conftest.py
tests/helpers/__init__.py
tests/helpers/cfchecking.py
tests/helpers/meta.py
tests/standardise/surface/test_btt.py
tests/standardise/surface/test_cranfield.py
tests/standardise/surface/test_crds.py
tests/standardise/surface/test_gcwerks.py
tests/standardise/surface/test_noaa.py
tests/standardise/surface/test_npl.py
tests/standardise/surface/test_thamesbarrier.py

This adds back in the CF compliance checking, see https://github.com/openghg/openghg/issues/206.

Add CF compliance checks

---

openghg/standardise/meta/_attributes.py
tests/helpers/cfchecking.py
tests/retrieve/test_search.py

This sets the CF compliance level to 1.8.

Updates to CF compliance level

---

openghg/standardise/meta/_attributes.py
openghg/standardise/surface/_btt.py
openghg/standardise/surface/_crds.py
tests/retrieve/test_search.py
tests/standardise/surface/test_btt.py
tests/standardise/surface/test_crds.py

Based on Issue #201, this includes updates to metadata and attributes where needed.
- metadata - BTT - inlet, instrument
- attributes - CRDS - 'sampling_period', 'instrument'
*Some outstanding questions on how to handle Cranfield data and NOAA updates are being added by PR #240.*

Updating metadata and attributes

---

openghg/analyse/_footprint.py
openghg/client/_observations.py
openghg/client/_search.py
openghg/data/acrg_site_info.json
openghg/dataobjects/_searchresults.py
openghg/retrieve/_access.py
openghg/util/_file.py
openghg/util/_util.py

Creating initial tutorial to add NOAA ObsPack to object store. This uses the `add_noaa_obspack()` function.

Obspack tutorial

---

.pre-commit-config.yaml
doc/source/development/python_devel.rst
requirements-dev.txt

This adds a pre-commit config file and updates the docs to include a guide on installing the hook.

Adding pre-commmit

---

openghg/client/_process.py
openghg/store/_footprints.py
tests/store/test_footprints.py

Updating footprint functions to make a distinction between high time resolution and high spatial resolution and the expectations around these inputs.
As well as applying updates to _footprint.py, also did the following:
- Updated and added new tests for _footprint.py
- Updated _process.py to incorporate updated keywords
Closes #294

Updating definition around high time and high spatial footprint resolution

---

doc/source/api/api_plotting.rst
doc/source/tutorials/index.rst
notebooks/tutorials/beginner_workflow/1_Adding_observation_data.md
notebooks/tutorials/beginner_workflow/2_Ranking_for_observations.ipynb
notebooks/tutorials/beginner_workflow/2_Ranking_for_observations.md
notebooks/tutorials/beginner_workflow/6_Searching_and_plotting.ipynb
notebooks/tutorials/beginner_workflow/6_Searching_and_plotting.md
openghg/dataobjects/_searchresults.py
openghg/plotting/_timeseries.py
openghg/retrieve/_search.py

This adds documentation for the new retrieval functionality in the `SearchResults` object. It also covers plotting a list of `ObsData` objects using the new-ish `plotting.plot_timeseries` function.

Adding SearchResults retrieval workflow and plotting to tutorials

---

.github/ISSUE_TEMPLATE/README.md
.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/config.yaml
.github/ISSUE_TEMPLATE/misc.yaml
.github/ISSUE_TEMPLATE/new_feature.yaml
.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
CODE_OF_CONDUCT.md
README.md
doc/source/development/python_devel.rst
doc/source/whatsnew/v0.1.0.rst

- Updating code of conduct,
- Updated python devel pre-commit section of docs,
- Added PR template

Adding community related files / docs

---

openghg/analyse/_scenario.py
openghg/dataobjects/_searchresults.py
openghg/retrieve/ceda/_retrieve.py
openghg/retrieve/met/_ecmwf.py
openghg/standardise/surface/_noaa.py
openghg/store/_footprints.py
openghg/transform/_regrid.py
openghg/transform/emissions/_edgar.py
tests/analyse/test_scenario.py
tests/store/test_ecmwf.py

This (thanks @rt17603) contains fixes / additions to our type hints to handle the new type hinting the xarray devs have added in their latest release.

`mypy` fixes for new xarray release

---

openghg/standardise/_standardise.py
openghg/store/_emissions.py

Updating docstrings for `standardise_*` functions to ensure all inputs are defined.
Closes #412

Updating docstrings for standardise functions etc.

---

.pre-commit-config.yaml
openghg/dataobjects/_obsdata.py
openghg/retrieve/_access.py
openghg/standardise/surface/_npl.py
openghg/store/_rank.py
openghg/store/base/_datasource.py
requirements-dev.txt

Fixes for mypy v0.991

---

mypy.ini
requirements-dev.txt

I've removed urllib3 requests section from the mypy.ini ignore.
Closes #209

Fix for types-urllib3 and mypy

---

openghg/dataobjects/_datahandler.py

Print statement showing uuid's is shifted inside for loop to show all the uuid's

updated indentation as per its mention in the issue.

---

.github/workflows/workflow.yaml

added python 3.11

---

README.md

Removes link to hugs-cloud.com

Update README link to point to repo

---

environment.yaml
mypy.ini
openghg/__init__.py
openghg/analyse/_scenario.py
openghg/store/_obssurface.py
openghg/store/_populate.py
openghg/util/_download.py
openghg/util/_versions.py
requirements.txt

This PR adds progress bars to the code using the rich package.

Iss 686 replaced tqdm to rich package progress bar

---

CHANGELOG.md

PR #718  was missing a change log entry, so I added it in this PR.

Change log fix-up

---

CHANGELOG.md
doc/source/development/quickstart_devel.rst
environment-dev.yaml

Added environment-dev.yaml file. Updated one documentation.

added environment-dev.yaml file

---

.github/workflows/workflow.yaml
openghg/analyse/_scenario.py
openghg/retrieve/_access.py
openghg/standardise/_summarise.py
openghg/standardise/emissions/_openghg.py
openghg/types/_enum.py
openghg/util/_domain.py
openghg/util/_inlet.py
openghg/util/_versions.py

- Added black format check before lint check in the CI.

added black check in the CI before lint

---

environment.yaml

environment.yaml file in openeghg missing openghg as a channel. Required for openghg env.

Updated openghg environment

---

doc/source/tutorials/local/Adding_new_data/Adding_observation_data.rst

Added the `What is Object Store' section` to the first tutorial as discussed.
* **Please check if the PR fulfils these requirements**

Iss547-Adding object store explanation

---

doc/source/tutorials/local/Adding_new_data/Adding_observation_data.rst

Added two code blocks showing what source formats are available, and what sites are available for "CRDS".

Added code blocks to tutorial 1 re: source format

---

doc/source/tutorials/local/Managing_object_store/Modifying_and_deleting_data.rst
openghg/dataobjects/_datamanager.py

Adds notes on metadata backup and updating multiple datasources.

Add extra notes about `DataManager` usage.

---

CHANGELOG.md

Update the changelog ready for release.

Update changelog ready for release

---

.pre-commit-config.yaml
environment-dev.yaml
requirements-dev.txt

Bump mypy version to 1.7.1

---

.github/workflows/workflow.yaml
environment-dev.yaml
environment.yaml
requirements.txt

This adds `filelock` to the the environment files.

Adding filelock to conda environemnt

---

openghg/dataobjects/_datamanager.py

Added store argument to the function search() inside _datamanager.py to show the store-specific results.

Added store argument to search

---

openghg/cloud/_call.py
openghg/dataobjects/_basedata.py
openghg/objectstore/metastore/_classic_metastore.py
openghg/objectstore/metastore/_metastore.py
openghg/retrieve/_export.py
openghg/retrieve/_search.py
openghg/store/_recombination.py
openghg/store/_segment.py
openghg/store/base/_base.py
openghg/transform/_transform.py
openghg/tutorial/_tutorial.py
openghg/util/__init__.py
openghg/util/_hashing.py
openghg/util/_inlet.py
openghg/util/_strings.py
openghg/util/_util.py
openghg/util/_versions.py
setup.cfg

I ran the new version of black over the codebase. Changes are minimal, mostly just changes to whitespace.

black, 1: Keep up to date with black formatting rules

---

.pre-commit-config.yaml
openghg/cloud/_call.py
openghg/dataobjects/_basedata.py
openghg/objectstore/metastore/_classic_metastore.py
openghg/objectstore/metastore/_metastore.py
openghg/retrieve/_export.py
openghg/retrieve/_search.py
openghg/store/_recombination.py
openghg/store/_segment.py
openghg/store/base/_base.py
openghg/transform/_transform.py
openghg/tutorial/_tutorial.py
openghg/util/__init__.py
openghg/util/_hashing.py
openghg/util/_inlet.py
openghg/util/_strings.py
openghg/util/_util.py
openghg/util/_versions.py
setup.cfg

> [!NOTE]  
> #895 should go in before this.
Updates the version of the tools in the pre-commit yaml.

black, 2: Updating versions of tools in pre-commit

---

openghg/store/storage/_localzarrstore.py
tests/store/storage/test_localzarrstore.py

This adds checking of current chunking to the `LocalZarrStore` class. When data is added to a current version the chunking of the incoming data is checked and compared with that in the currently stored data. If it's different then the incoming data is rechunked to match that of the stored data and the user is informed of this.

Check current chunks

---

openghg/standardise/_standardise.py
openghg/standardise/column/_openghg.py
openghg/standardise/flux/_intem.py
openghg/standardise/flux/_openghg.py
openghg/store/_boundary_conditions.py
openghg/store/_eulerian_model.py
openghg/store/_flux.py
openghg/store/_footprints.py
openghg/store/_obscolumn.py
openghg/store/_obssurface.py
tests/standardise/test_standardise.py

Adds chunk argument to all standardise functions and storage_type.read_file functions.

Chunk all types

---

openghg/store/base/_datasource.py
openghg/store/storage/_localzarrstore.py
tests/dataobjects/test_datamanager.py
tests/db_integrity/test_data_updates.py
tests/retrieve/test_search.py
tests/store/storage/test_localzarrstore.py
tests/store/test_datasource.py

This move the firs version in the object store from v0 to v1.

Move from first version being v0 to v1

---

openghg/util/_hashing.py
tests/util/test_hashing.py

Fixes the hash test error in `test_hash_retrieved_data`

Fix for `test_hash_retrieved_data`

---

.github/workflows/workflow.yaml
codecov.yml

This removes codecov as it's adding itself to PRs where it's not wanted and its coverage isn't correct for us.

Remove codecov

---

CHANGELOG.md
doc/source/tutorials/local/Adding_data/Adding_ancillary_data.rst
openghg/analyse/_scenario.py
openghg/retrieve/_search.py
openghg/standardise/_standardise.py
openghg/standardise/footprint/_acrg_org.py
openghg/store/_footprints.py
openghg/tutorial/_tutorial.py
tests/analyse/conftest.py
tests/db_integrity/test_data_updates.py
tests/retrieve/conftest.py
tests/retrieve/test_search.py
tests/store/test_footprints.py

Renaming the metmodel keyword to met_model to better align with other keywords like this and expectations within attributes.
***Builds on PR #955 - so that PR should be reviewed and merged first***
Shouldn't be needed for this change:

Rename metmodel to met_model

---

openghg/data/process_gcwerks_parameters.json

Add an entry for Taunus (TOB) site in process_gcwerks_parameters.json

Add TOB entry to process_gcwerks_parameters.json

---

CHANGELOG.md
openghg/standardise/_standardise.py
openghg/standardise/meta/_attributes.py
openghg/standardise/surface/_crds.py
openghg/standardise/surface/_gcwerks.py
openghg/standardise/surface/_icos.py
openghg/standardise/surface/_noaa.py
openghg/standardise/surface/_openghg.py
openghg/standardise/surface/_thamesbarrier.py
openghg/store/_obssurface.py

Update `supplementary_data` to `openghg_defs`

Update `supplementary_data` to `openghg_defs`

---

doc/source/tutorials/local/Exploring_data/Searching_and_plotting.rst

Remove the ipython directive from docs

Remove leftover ipython directives blocking doc build

---

openghg/util/_export.py

Adds the `to_dashboard_agage` function which allows multifile export for AGAGE or similar dashboards.

Add `to_dashboard_agage` for possible future use

---

CHANGELOG.md
openghg/analyse/_scenario.py

Change `base` to `offset` due to deprecation.

Changed base to offset

---

CHANGELOG.md

These were in the wrong locations

Moved changelog items from 0.8.2 to 0.9

---

openghg/retrieve/icos/_retrieve.py

Added dataset_formatter before assign_attributes in retrieve_icos to update the data variables.

Added dataset_formatter added to retrieve-icos

---

doc/source/api/devapi_standardise.rst
openghg/standardise/column/_openghg.py
openghg/standardise/meta/__init__.py
openghg/standardise/meta/_metadata.py
openghg/standardise/surface/_agage.py
openghg/standardise/surface/_openghg.py
tests/standardise/column/test_openghg_column.py
tests/standardise/surface/test_openghg_surface.py

Replaced metadata_default_keys to attributes_default_keys
Updated required variable names

Replaced metadata_default_keys to attributes_default_keys

---

CHANGELOG.md
tests/standardise/surface/test_agage.py
tests/standardise/surface/test_crds.py
tests/standardise/surface/test_gcwerks.py
tests/standardise/surface/test_noaa.py
tests/standardise/surface/test_npl.py
tests/standardise/surface/test_openghg_surface.py

Currently failing due to HTTPError, caused by broken link to cf conventions xml file.

Added xfail for cfchecker tests

---

CHANGELOG.md
openghg/retrieve/icos/_retrieve.py

Added dobj_url as attribute to retrieve_atmospheric function

Added dobj url as an attribute

---

.github/workflows/workflow.yaml
CHANGELOG.md
environment.yaml
openghg/__init__.py
setup.cfg
setup.py

Updated `setup.py, setup.cfg`, and workflows to make minimum python version 3.10. This is needed to get the latest bugfixes for zarr.

Updated min python version to 3.10

---

CHANGELOG.md
openghg/retrieve/icos/_retrieve.py

This PR contains changes merged from file retrieve.py of branch https://github.com/openghg/openghg/pull/1196/files#diff-319a49efc65904c8af95625e968a62a6ff3fbbe4442b109905f1004d6e870d10 whilst maintaining the bug fix of sync surface metadata.

Merged changes from retrieve.py file of branch Iss1190/icos_flags

---

CHANGELOG.md
environment-dev.yaml
environment.yaml
requirements.txt

Pinned the version of zarr to 2.18.3. Version 3.0 of zarr is still significantly under development.

Mypy issues

---

CHANGELOG.md
openghg/data/config/objectstore/defaults.json
openghg/standardise/_standardise.py
openghg/store/_obscolumn.py
tests/standardise/test_standardise.py

Added region arg to standardise column. Updated tests to check the new args.
Added ObsColumn to accept region arg

Standardise column and pipeline to incorporate additional keys

---

CHANGELOG.md
openghg/analyse/_scenario.py
openghg/util/__init__.py
openghg/util/_util.py
tests/analyse/conftest.py
tests/analyse/test_scenario.py

Configure ModelScenario to handle satellite data for column and footprints

---

CHANGELOG.md
openghg/data_processing/_resampling.py
openghg/retrieve/_access.py
tests/analyse/conftest.py
tests/analyse/test_scenario.py
tests/data_processing/test_attrs.py
tests/data_processing/test_resampling.py
tests/dataobjects/test_datamanager.py
tests/datapack/test_obspack.py
tests/helpers/helpers.py
tests/objectstore/test_config.py
tests/retrieve/icos/test_retrieve_icos.py
tests/standardise/boundary_conditions/test_openghg.py
tests/standardise/eulerian_model/test_parse_openghg.py
tests/standardise/footprints/test_acrg_org.py
tests/standardise/surface/test_niwa.py
tests/standardise/test_standardise.py
tests/store/test_boundary_conditions.py
tests/store/test_flux.py
tests/store/test_obssurface.py
tests/util/registry_aux.py
tests/util/test_util.py

Fix small stuff in openghg/retrieve/_access.py `get_obs_surface` : 
- raise a SearchError if data retrieved by _get_generic are empty
- add a check to delete `"flag"` variable (when exists) and all values equal to `'O'` or `'U'`
- check if variables are full of nans and delete them if so 
Create a new resampling function `mean_and_variability_resample` in openghg/data_processing/_resampling.py `_surface_obs_resampler_dict` when there is `f"{species}_variability"` and no `f"{species}_number_of_observations"` : this function creates the variable  `f"{species}_number_of_observations"` full of ones and then calls `weighted_resampled`.

Fix issue #1274

---

CHANGELOG.md
requirements.txt

Pinned numcodecs for less than 0.16

Pinning numcodecs

---

CHANGELOG.md
openghg/data_processing/_resampling.py
tests/analyse/test_scenario.py
tests/data_processing/test_resampling.py
tests/util/test_platform.py

Replace nans with zeros for variables "{species}_variability" and "{species}_repeatability" during resampling to prevent dropping of all data when one of this variables is almost filled with nans.

Fix issue 1297

---

CHANGELOG.md
openghg/util/_combine.py

Refactored the import function of xarray Coordinates by changing import to
from xarray.core.coordinates import Coordinates

Resolving documentation build failure 

---

CHANGELOG.md
environment-dev.yaml
environment.yaml
mypy.ini
openghg/retrieve/_access.py
pyproject.toml
requirements.txt
tests/retrieve/test_access.py

Added openghg_calscales as a dependency.
Replaced the previous "_scale_convert" function with "convert" from openghg_calscales.
Added test

Update get obs function with calscales repo functions

---

CHANGELOG.md
doc/source/tutorials/local/Analysing_data/Comparing_with_emissions.rst
openghg/analyse/_scenario.py

Plotting was failing and required the plot to be directed at the data in the modelled observations.

Added 'mf_mod' in tutorial plot

---

.github/pull_request_template.md

Updated the PR template to better align with things we want to individually check. Summary:
- Include documentation and tutorial updates as separate bullet points
- Add in wiki check
- Add a note to remove the checkboxes if not needed (e.g. CHANGELOG doesn't always need updating for internal changes or new requirements are not needed)
Not needed
- Closes #xxxx (Replace xxxx with the Github issue number)
- Documentation and tutorials updated/added

Update pull_request_template.md to split out documentation, tutorials and add wiki

---

openghg/dataobjects/_basedata.py

Improved `__repr__` of `_BaseData` so that it is more likely to print useful info.
Also fixed issue where it would try to remove "data_type", which could fail if the data object was created with empty metadata.
- Closes #xxxx (Replace xxxx with the Github issue number)
- [Tests added and passed](https://docs.openghg.org/development/python_devel.html#testing) if fixing a bug or adding a new feature
- All code checks passing - `black --line-length 110` run over code, `mypy` and `flake8` not showing any errors
- Documentation updated/added
- Tutorials updated/added
- Wiki updated
- …

Improve _BaseData repr

---

.github/workflows/workflow.yaml
pyproject.toml

Updated anaconda token and verison in pyproject.toml

updated token and release version

---

openghg/util/_versioning.py
tests/util/test_versioning.py

Some simplifications to a previous PR #1356. There are also some changes that are needed by future PRs like #1391.
- Closes #xxxx (Replace xxxx with the Github issue number)
- [Tests added and passed](https://docs.openghg.org/development/python_devel.html#testing) if fixing a bug or adding a new feature
- Tutorials updated/added
- Wiki updated
*Note: if any of the above are not needed for a PR please separate to below and remove the checkbox.*

Versioning simplifications
