openghg/openghg

- openghg/processing/_observations.py
- openghg/processing/_search.py
I think get_observations was calling ```search``` with the "locations" keyword, whereas the metadata expects "site". I changed these.
Also, I changed the call to ```search``` to have ```find_all=False```, as it wasn't returning anything if e.g. you specified the site and species (because inlet, etc weren't defined). Is that right?
However, get_observations still doesn't work. It only returns one year of data. Is this because of this line:
```site_key = list(obs_results.keys())[0]```
(_observations.py Line 115)
I can't understand the logic of this, and it seems to then only be recombining one year of data
> Bug fixes in get_observations

- openghg/modules/_base.py
- openghg/modules/_emissions.py
- openghg/modules/_footprints.py
- openghg/modules/_metstore.py
- openghg/modules/_obs_surface.py
- tests/modules/test_obssurface.py
This moves some code into the base class which makes it easier to create new classes (for footprints, emissions etc) and cuts down on code replication for the `from_data` / `to_data` functions.
> Moving code into BaseModule class

- openghg/modules/_gcwerks.py
- openghg/processing/_recombination.py
- tests/localclient/test_get_surface_obs.py
- tests/mock/hugs/test_process.py
- tests/modules/test_gcwerks.py
- tests/modules/test_obssurface.py
- tests/processing/test_recombination.py
- tests/processing/test_search.py
This updates the labelling on inlets to use the `inlet_labels` values given in `process_gcwerks_parameters.json` rather than the inlet value given in the data. This fixes the duplication of datasources when inlets such as `75m_4` are used in the data. These now map to `70m` on read.
> Inlet labels now used instead of labels read directly from data

- .github/workflows/main.yaml
This adds checks in for the bash script that's pulled down from CodeCov and pins the `JamesIves/github-pages-deploy-action` to a fixed commit hash.
> Updating the GitHub actions workflow to check CodeCov SHAs and commit hash of action

- openghg/localclient/_rank_sources.py
- openghg/modules/_base.py
- openghg/modules/_datasource.py
- openghg/util/__init__.py
- openghg/util/_time.py
- tests/modules/test_obssurface.py
- tests/util/test_time.py
This adds some code to allow the overwriting of rankings in a better way. We can now overwrite ranks and the dateranges are all split and ranks reassigned automatically.
> Rework of how ranks are stored and how overwriting happens

- openghg/processing/_observations.py
- openghg/processing/_process_footprint.py
- tests/helpers/__init__.py
- tests/helpers/helpers.py
Uses input "sampling_period" attribute when deciding on resampling strategy for footprints and data.
If this attribute is not present this will still attempt to derive this from the obs data frequency but will produce an error is this is too variable. This is an alternative to the suggested approach on applying a default sample_period of "1H".
Other changes:
- The default for the `resample_to` input parameter has also been updated to "coarsest" (instead of "obs") as this is more appropriate for expected inputs.
- This can now be used for "flask" samples as long as the "sample_period" is specified.
- Using `get_obs_surface()` will now add "averaged_period" and "averaged_period_str" attributes to the output Dataset (this is not used anywhere yet but plan to use this within …
> Updated resampling when combining footprints and obs data

- openghg/standardise/surface/_gcwerks.py
- tests/localclient/test_get_surface_obs.py
- tests/retrieve/test_recombination.py
- tests/services/test_process.py
- tests/standardise/surface/test_gcwerks.py
- tests/store/test_obssurface.py
Closes #169
Updated the species name to be the same between the label in the retrieved data and the variable within Dataset.
Uses attributes.json file (as does the attributes function) to look up standard name and use this when creating the species label e.g. "toluene_70m" would now be "c6h5ch3_70m"
Associated tests also updated to align with this new naming scheme.
> Standardising species name for GC

- openghg/standardise/surface/_aqmesh.py
- openghg/standardise/surface/_glasgow_licor.py
- openghg/standardise/surface/_glasgow_picarro.py
- tests/standardise/surface/test_aqmesh.py
- tests/standardise/surface/test_glasgow_licor.py
- tests/store/test_obssurface.py
- tests/util/test_export.py
Based on Issue #84 but does not fully close this.
Updating standardisation functions to include the same default sampling period of "NOT_SET" when this value is not supplied or can't be read elsewhere.
> Standardisation to default sampling period when this is not set

- openghg/client/_rank_sources.py
- openghg/data/site_lookup.json
- openghg/standardise/surface/_crds.py
- openghg/standardise/surface/_gcwerks.py
- openghg/store/_obssurface.py
- openghg/util/__init__.py
- openghg/util/_strings.py
- openghg/util/_util.py
- requirements.txt
- tests/standardise/surface/test_crds.py
- tests/standardise/surface/test_gcwerks.py
- tests/util/test_util.py
This allows the passing of names like `cape grim` instead of `CGO` and `angus tower` instead of `TTA`. Slightly mis-spelt words should also be matched as `rapidfuzz` has been used for some simple fuzzy text matching. This should close #204.
> Ability to pass site long name to processing scripts

- openghg/standardise/meta/_metadata.py
`long_name` gets converted to `station_long_name` in https://github.com/openghg/openghg/blob/d4d476707ded1df2822e8f9ee5244ca015c25eca/openghg/standardise/meta/_attributes.py#L307.
This just removes `long_name` from the list of expected keys.
> Fix for `long_name` warnings

- openghg/store/base/_datasource.py
- tests/store/test_datasource.py
This fixes the warning when finding dataset dateranges, closes #228.
> Fix for FutureWarning error in Datasource

- openghg/standardise/surface/_crds.py
- openghg/standardise/surface/_gcwerks.py
Whilst doing some profiling to look at the fragmented dataframe warning (#111) I found that the time parsing for GCWERKS and CRDS data was very slow. I've made some small changes to speed things up a bit.
The main change was removing the use of `date_parser` and doing pd.to_datetime(index) instead.
> Date parsing speedup

- openghg/standardise/surface/_gcwerks.py
This fixes #111 by joining all the status flag columns in a single `join` in the gcwerks processing function.
> Fix for pandas DataFrame fragmentation warning.

- README.md
Added fix to "Additional Functionality" instructions in README (and an extra caveat). This is related to the installation of the `xesmf` module for additional tranform functionality.
> Fix mistake in additional functionality instructions in README.md.

- openghg/analyse/_scenario.py
- openghg/exceptions/__init__.py
- openghg/retrieve/_access.py
- openghg/retrieve/_search.py
- openghg/types/__init__.py
- openghg/types/_errors.py
- tests/analyse/test_scenario.py
- tests/retrieve/test_access.py
Ensuring behaviour for openghg.retrieve.get_* functions is consistent and adding custom `SearchError` function for openghg
- If no results found returns a `SearchError` with helpful message (restates keys which were passed in)
- If multiple results are found returns `SearchError` with helpful message (compares metadata and prints differences)
- All functions (including get_obs_surface_local) are now fed through _get_generic function
`openghg.analyse._scenario` has also been updated to account for this behaviour (interface and output from ModelScenario class and methods should be the same).
Closes #297, #416
> Harmonising get functions to produce same errors

- openghg/analyse/_scenario.py
- openghg/retrieve/_access.py
- openghg/retrieve/_search.py
- openghg/store/_footprints.py
- openghg/store/_obssurface.py
- openghg/util/__init__.py
- openghg/util/_inlet.py
- tests/retrieve/test_access.py
- tests/retrieve/test_search.py
- tests/store/test_footprints.py
- tests/util/test_inlet.py
At the moment, we have an input of `inlet` for ObsSurface data and `height` for Footprint data when they should represent the same property (and most of the time will be equivalent). 
This update makes the following changes:
- Adds "inlet" as an additional input and metadata keyword within the `Footprint.read_file()` method
-  This still retains "height" for backwards compatability but this should always be the same as the `inlet` value
- Adds "inlet" to both `search_footprints` and `get_footprint` functions. Either inlet or height can be used to search.
- Also allows "height" as an alias input for "inlet" within `ObsSurface.read_file`
-  "height" is not added to the metadata here as this is not needed for backwards compatability
- Adds "height" to both `search_surface` and …
> Adding inlet as keyword and allowing height as an alias for both footprints and obs_surface

- environment.yaml
Moved `icoscp` to pip section of environment.yaml and corrected `msgpack` package name to `msgpack-python`.
Need to do some additional checks to make sure this works correctly so a draft for now.
> Fix conda install instructions

- openghg/store/base/_base.py
- openghg/util/_export.py
Getting a weird circular import error on some machines when `to_lowercase` is imported. Hopefully this will fix it.
> Move to_lowercase to function scope import

- openghg/analyse/_scenario.py
- openghg/retrieve/_access.py
- openghg/standardise/meta/_attributes.py
- openghg/standardise/surface/_crds.py
- openghg/store/_infer_time.py
Running:
```
$ pytest -v tests/analyse/test_scenario.py
```
Among others, the following warning was being returned:
```
xarray/core/indexes.py:97: FutureWarning:
Indexing a timezone-naive DatetimeIndex with a timezone-aware datetime 
is deprecated and will raise KeyError in a future version.  Use a timezone-naive object instead.
```
Added a fix for this and for a few small additional warnings.
*Note: used the warnings module to pinpoint the origin of the warning.*
```
$ PYTHONWARNINGS=error::FutureWarning pytest -v tests/analyse/test_scenario.py
```
Closes #353
Closes #433 
Closes #434
> Added fixes for warnings related to _scenario.py

- .github/workflows/workflow.yaml
- doc/source/api/api_tutorial.rst
- openghg/standardise/_standardise.py
- openghg/standardise/surface/_crds.py
- openghg/standardise/surface/_gcwerks.py
- openghg/standardise/surface/_icos.py
- openghg/standardise/surface/_noaa.py
- openghg/standardise/surface/_openghg.py
- openghg/standardise/surface/_thamesbarrier.py
- openghg/store/_obssurface.py
- openghg/tutorial/__init__.py
- openghg/tutorial/_tutorial.py
- tests/conftest.py
- tests/data/info/site_info.json
- tests/tutorial/test_tutorial.py
- tests/util/test_site.py
Two main changes within this PR:
- Adding `site_filename` as an input for front-end functions. This allows a "site_info.json" file to be specified directly rather than using the "site_info.json" file available from the `openghg_defs` dependency. This includes:
- `ObsSurface.read_file` method
- `standardise_obs` function
- `parse_*` functions (where appropriate) this includes:
- `parse_crds`, `parse_gcwerks`, `parse_icos`, `parse_noaa`, `parse_openghg`, `parse_tmb`
- NOT added for others as these often did not include link with direct/indirect calls to `get_site_info()` which is the function that calls `openghg_defs`
- Mocking the call to `openghg_defs` within the tests to use a static version of "site_info.json" within tests data folder.
The second fix is to ensure the tests aren't …
> Adding ability to use alternative site_filename and adding mock to use static version in tests

- openghg/standardise/surface/_gcwerks.py
- openghg/store/_obssurface.py
- tests/standardise/surface/test_gcwerks.py
- tests/store/test_obssurface.py
Updating a few bugs in sampling period checking:
- updating checks within `ObsSurface.read_file()` on whether this has been specified incorrectly (based on current documentation i.e. doesn't contain a unit). Updated to explicitly check whether this can be evaluated to just a number and raising a ValueError.
- updating logic within `parse_gcwerks()` - converting sampling period to a Timedelta was raising a ValueError as this was a string when a float was expected by the function.
Closes #583
> Fix bug in sampling period checking

- openghg/util/_user.py
Previously, if a user didn't enter path when promoted during create_config, the default path was being overwritten.
For me, the tests for these functions don't work. It could be to do with the mocking. I get errors when the tests try to clean up the testing store, like:
No such file or directory: '/var/folders/ck/vrz4wwp115qb8jbc7y_wk1r00000gq/T/openghg_testing_store
> Fixed logic for specifying default objectstore path in config file

- environment.yaml
- requirements.txt
The upgrade to pandas 2.0 seems to have caused a set of tests to fail. Suggest pinning this to 2.0 to allow development to continue until we can address these issues.
Relates to #618
> Temporarily pinning pandas to < 2.0

- openghg/retrieve/icos/_retrieve.py
This closes #599 . There was a missing sampling_height argument in the call to _retrieve_remote from local_retrieve within openghg.retrieve.icos. This meant that it wasn't possible to filter by sampling_height.
> Make ICOS retrieval function filter by sampling height correctly

- tests/conftest.py
This adds a catch for the FileNotFoundError which is raised when individual tests are run but nothing is written to the object store.
> Catch edge case where nothing is written to the store

- openghg/dataobjects/_obsdata.py
- openghg/plotting/_timeseries.py
Updating the relevant method on ObsData to use the plot_timeseries() function directly. This is to ensure optimisation and changes don't have to be made twice.
See comments on PR #614
> Updating ObsData.plot_timeseries() method to use openghg.plotting.plot_timeseries() function

- doc/source/development/python_devel.rst
Some quick notes on the steps required to create a new release of OpenGHG. Closes #644.
> Notes no how to do a release

- openghg/retrieve/icos/_retrieve.py
- tests/retrieve/icos/test_retrieve_icos.py
At the moment the `retrieve_atmospheric` function uses internal attributes to directly create the metadata. This update is to allow these internal values to checked against the site_info data and spot mismatches (these can be allowed to be updated if needed).
This also reduces the expected metadata keys for the ICOS data and adds `inlet` in preference to `sampling_height` to align with other source_formats for the `obs_surface` data type.
Closes #656
> Allowing ICOS internal attributes and data derived from site_info to be compared

- .pre-commit-config.yaml
- requirements-dev.txt
* Type-UPDATE
* The earlier pinned version of mypy is now updated to the latest released version 1.4.0. inside requirements-dev.txt and pre-commit-config.yaml too.
> removed pinned mypy version and update to 1.4.0

- openghg/store/base/_base.py
- openghg/store/base/_datasource.py
- tests/helpers/helpers.py
This fixes the issue with the object store path being lowercased in the metadata resulting in
paths with uppercase letters being invalid on case-sensitive systems. It does this by allowing the passing in
of a `skip_keys` value in the `BaseStore.assign_data` function which is passed down to `Datasource.add_metadata`.
> Iss701 - Fix lowercasing of metadata causing object store lookup issues

- CHANGELOG.md
- openghg/dataobjects/_datamanager.py
- tests/dataobjects/test_datamanager.py
Fixes a bug where a string was interpreted as a list when deleting metadata keys in `DataManager`
> Fix for string being interpreted as list on key delete in DataManager

- CHANGELOG.md
- openghg/store/base/_base.py
- tests/conftest.py
- tests/store/test_obssurface.py
This stops the saving of the bucket path to the object JSON and updates the base store constructor so the class variable is assigned to after the JSON data is loaded in. This should allow this update to fix the issue without any intervention from the user.
> Fix for bucket being saved to JSON

- .github/workflows/workflow.yaml
This adds the OpenGHG conda channel. It's done this way using `conda config --append ...` to avoid issues with conda thinking the local openghg folder is a channel and erroring.
> Add openghg conda channel

- CHANGELOG.md
- openghg/retrieve/_search.py
- openghg/store/_metadata.py
- openghg/types/__init__.py
- openghg/types/_errors.py
- tests/store/test_metastore.py
This enables the read-only opening of the metastore by passing the a `mode` keyword to `load_metastore` and the constructor of the store.
> Enable read-only opening of metastore

- CHANGELOG.md
- openghg/objectstore/__init__.py
- openghg/objectstore/_local_store.py
- openghg/store/base/_datasource.py
- tests/store/test_datasource.py
- tests/store/test_obssurface.py
1. Compression level for saving Datasources is increased from 4 to 5.
(Compression level 4 seems to be the default.) I added a test to show
that increasing compression does actually result in small files on disk.
2. `Datasource.load_dataset` now uses `xarray.open_dataset` instead
of `xarray.load_dataset`, which should lazy-load data. This gives a 
33% decrease in the time taken to run all of the tests on my machine.
I couldn't make a useful test to demonstrate that data is lazy-loaded,
but the xarray docs state that this is the case:
https://docs.xarray.dev/en/latest/user-guide/io.html#reading-encoded-data
(They say data is "always lazy loaded from netcdf", although the docs for
`load_dataset` say the opposite.)
*If* …
> Iss749 add compression

- .github/workflows/workflow.yaml
This should make it so that changing the change log doesn't trigger CI.
> Added CHANGELOG.md to push paths-ignore

- CHANGELOG.md
- openghg/standardise/surface/_btt.py
- openghg/standardise/surface/_cranfield.py
Added deprecation warning to the parse function of Cranfield and BTT.
**Not Required**
> added deprecation warnings to parse function for cranfield and btt

- CHANGELOG.md
- openghg/retrieve/icos/_retrieve.py
Added conversion of species to lower if filtered sources are empty. As it was not detecting species like radon.
**Not Required**
- Documentation and tutorials updated/added
> Bug fix to retrieve `radon` using retrieve_atmospheric

- .github/workflows/workflow.yaml
- CHANGELOG.md
- openghg/__init__.py
Dropping support for Python 3.8. This has become necessary because the dependencies for openghg no longer support it (e.g. `xarray` dropped support as of [v2023.02.0](https://docs.xarray.dev/en/stable/whats-new.html#v2023-02-0-feb-7-2023)).
As a part of this, this also adds a check for [Python 3.12](https://www.python.org/downloads/release/python-3120/) which was released on 02/10/2023.
* **Additional note**
Had to update branch protection rules on GitHub for both `devel` and `master` to remove "Run the tests (3.8)" from the list of checks and replace this with "Run the tests (3.11)".
> Dropping support for Python 3.8 and adding Python 3.12

- tests/util/test_site.py
Some of the parameterised tests in `tests/util/test_site.py::test_sites_in_network` had been commented out (in 02/2023 [as part of commit 87f90e1](https://github.com/openghg/openghg/pull/537/commits/87f90e16da2bee565a0744709adbbb86ee655725#diff-5166e94f0cd4b507533b4b27567723ced669d5c847501a9fc548edcee5835ab1)) but there doesn't seem to be a reason for these tests to not be included. These tests are able to pass and do include more testing for the specified function.
> Adding back commented out tests in test_site.py for sites_in_network

- CHANGELOG.md
- openghg/retrieve/icos/_retrieve.py
- openghg/store/_obssurface.py
- tests/retrieve/icos/test_retrieve_icos.py
Added `force` option to `retrieve_atmospheric` and `ObsSurface.store_data`. If `force=True`, then retrieved hashes will be ignored.
Two tests were added, one to check that if `force=False` (the default option) then `retrieve_atmospheric` issues a warning that there is no new data to process. If `force=True`, then this warning is not issued (and the data is added again, although this is not explicitly checked).
> Iss #815 fix for re-adding ICOS data after removing it

- openghg/store/_obssurface.py
The `force` keyword was added for ObsSurface.add_data to fix issue observed in #815 (PR #819 ) but for the new functionality of `new_object_store` this also needs the `if_exists` keyword to be set to an appropriate value to let this add to the object store. This adds an additional update for this.
Without this the retrieve icos `test_force_allows_storing_twice` was failing - this fixes that.
> Updating new_object_store to incorporate `force` keyword on add_data

- .github/workflows/workflow.yaml
- .pre-commit-config.yaml
- CHANGELOG.md
- pyproject.toml
Black is configured using the `pyproject.toml` file (unlike flake8, which is configured in the setup.cfg file).
Putting `line-length=110` in the pyproject toml means that this setting can be found by IDEs.
> Added black line length = 110 to toml

- CHANGELOG.md
- openghg/objectstore/metastore/_classic_metastore.py
- tests/objectstore/test_classic_metastore.py
* **Summary of changes** (Bug fix, feature, docs update, ...)*
Custom TinyDB middleware was added to cache writes to the metastore and
only write the changes if the metastore has not changed on disk.
If there are cached writes and the metastore has changed on disk, then a `MetastoreError`
is raised and the cached changes are not saved.
> Iss764: cache metastore writes and only update if "safe"

- doc/source/tutorials/local/Adding_new_data/Adding_ancillary_data.rst
- doc/source/tutorials/local/Analysing_data/Comparing_with_emissions.rst
Adding requested change to tutorial documents (from umbrella issue - #547 ). This is to add reference to the specific LPDM model methodology used to create the footprint format we accept in OpenGHG.
> Adding reference to LPDM model used to tutorial details

- CHANGELOG.md
- doc/source/development/python_devel.rst
- doc/source/development/quickstart_devel.rst
- doc/source/install.rst
- doc/source/packaging.rst
In v0.7.0 support for Python 3.8 will be dropped. This change updates the documentation to include references to Python >=3.9 (and current support for 3.9 - 3.12).
> Updating documentation to remove references to Python 3.8

- openghg/objectstore/__init__.py
- openghg/objectstore/_local_store.py
- openghg/objectstore/metastore/__init__.py
- openghg/objectstore/metastore/_classic_metastore.py
- openghg/store/base/_base.py
- requirements.txt
- tests/objectstore/test_file_locks.py
- tests/objectstore/test_local_object_store.py
`ClassicMetaStore` was removed and replaced by `DataClassMetaStore`, 
since only the children of `BaseStore` use `ClassicMetaStore` directly.
`open_metastore` now uses `TinyDBMetaStore` directly.
This means that we don't need a class method for use in `BaseStore`.
File locks were added to `DataClassMetaStore`, and used in `BaseStore.assign_data`.
Tests were added to show that
1) the locks stop other instances of `DataClassMetaStore` from acquiring a lock on a locked file
2) the locks are "advisory", meaning that they don't actually stop access to the file. So, read operations
work on locked files. (This also means that we might need to add locks to other places where write operations occur.)
This could be improved by making the …
> Iss695 object store lockfile

- openghg/analyse/_scenario.py
- openghg/data/process_gcwerks_parameters.json
- openghg/standardise/surface/_gcwerks_nc.py
- tests/db_integrity/test_data_updates.py
- tests/retrieve/test_access.py
- tests/standardise/surface/test_gcwerks.py
- tests/standardise/surface/test_gcwerks_nc.py
Made some changes so that we can load Matt's combined (i.e. more than one instrument) .nc files:
- Get the correct instrument name from the filename
- Added relevant entries to json file - setting sampling_period to "varies"
- Handle this in the model scenario code
- Adjust the timestamp based on the sampling_period read from the file, rather than from the json
- Change the GCMD sampling_period in the json to 1s (this has always been an instantaneous measurement)
- Change tests accordingly
Some tests are failing, but the same tests fail for me on the agage_new_format branch. So I think we can merge these changes into that branch, then fix remaining issues when we merge agage_new_format back to devel.
> Load Matt's combined .nc files

- openghg/dataobjects/_basedata.py
- openghg/standardise/_standardise.py
- openghg/store/_footprints.py
- openghg/store/base/_datasource.py
- openghg/store/storage/_compression.py
- tests/dataobjects/test_obs_dataclass.py
- tests/store/test_datasource.py
* **Summary of changes** 
This:
- Closes #874 
- Removes the rechunking and sorting from `add_timed_data`
- Adds a sort to ObsData which is very quick
- Allows you to just pass `chunks` into the xarray open(mf)_dataset functions
Note that this means the data is in the zarr store in the order it's added and so needs sorting before the user uses it. This reduces complexity on the way in and should hopefully be quite quick on retrieval (from my limited tests anyway).
> Reduce rechunking and sorting

- CHANGELOG.md
- openghg/retrieve/_access.py
* Added use of synonyms function inside get_obs_surface_local. This ensures the conversion of species parameters passed to have the name of species in cohesion with the openghg.
* **Not required**
*
> Bugfix_862_get_obs_surface

- openghg/store/storage/_localzarrstore.py
- tests/standardise/test_standardise.py
- tests/store/storage/test_localzarrstore.py
This makes sure incoming data with different chunks is actually stored with the original schema. In the current version if data is passed in with different chunks then the rechunk in `LocalZarrStore.add` doesn't get rid of the chunks in different coordinates.
> Ensure dataset chunking matches what's already there

- openghg/store/storage/_localzarrstore.py
`xr.Dataset.dims` returns a `Mapping` with `Hashable` keys, while
our chunk `dict` specify strings for keys. To appease mypy, I converted
the Hashable keys to strings. (It is conceivable that a dim is some
Hashable with no custom str method, so the call to `str` would return
the `repr` instead, which might be ugly... but at least it will never
cause an error.)
> Mypy fix for local_zarr_store

- openghg/util/_hashing.py
- tests/util/test_hashing.py
The test `test_hash_retrieved_data` started failing recently, possibly due to an upstream change. I updated the "expected" hashes and now the test passes reliably.
> Hashing test fix

- openghg/analyse/_scenario.py
I forgot to change one of the type annotations for `ModelScenario.__init__` so that this now fails the checks for mypy.
```
$ mypy openghg/
openghg/analyse/_scenario.py:174: error: Argument "store" to "add_obs" of "ModelScenario" has incompatible type "str | list[str] | None"; expected "str | None"  [arg-type]
openghg/analyse/_scenario.py:199: error: Argument "store" to "add_footprint" of "ModelScenario" has incompatible type "str | list[str] | None"; expected "str | None"  [arg-type]
openghg/analyse/_scenario.py:211: error: Argument "store" to "add_flux" of "ModelScenario" has incompatible type "str | list[str] | None"; expected "str | None"  [arg-type]
openghg/analyse/_scenario.py:222: error: Argument "store" to "add_bc" of …
```
> Fixup for pr928

- .github/workflows/conda.yaml
- .github/workflows/workflow.yaml
This adds the verbose flag to the CI so we can hopefully diagnose slow / stuck tests easier. Doesn't have to be merged but I want the CI to run.
> Find the stuck test

- environment-dev.yaml
- pyproject.toml
- requirements-dev.txt
This adds the [`pytest-timeout`](https://github.com/pytest-dev/pytest-timeout) plugin which will stop any individual tests after they've run for a specified time, here 60s.
> Adding pytest-timeout to stop any tests taking longer than 300s

- pyproject.toml
This corrects the header so pytest reads from the `pyproject.toml` file properly.
> Correct header for pytest to read from pyproject.toml

- .github/workflows/workflow.yaml
- doc/source/packaging.rst
- recipes/meta.yaml
The value for the git tag is now fetched from the environment and passed into the conda recipe for the conda build.
This ensures that the conda build on the master branch works as expected when the master is tagged instead of devel.
> Update meta.yaml and workflow to fetch git tag on master

- openghg/objectstore/_local_store.py
- openghg/util/_user.py
- tests/util/test_user.py
* **Summary of changes** 
This adds some functionality to the `read_local_config` function to check for old non-Zarr object stores and remove them from the config dictionary that OpenGHG will use internally when doing lookups etc. This does **not** remove them from the config file on disk. 
It could be some useful temporary functionality to allow users to have multiple virtual environments and versions of OpenGHG in use whilst populating their new store / new shared stores are populated.
This also means they can have new and old stores in their config file whilst the changeover happens.
> Temporary check for old object stores when using `0.8.0`

- CHANGELOG.md
- doc/source/tutorials/index.rst
- doc/source/tutorials/local/Managing_object_store/Converting_a_store.rst
- openghg/objectstore/metastore/_classic_metastore.py
- openghg/standardise/_standardise.py
- openghg/standardise/surface/_openghg.py
- openghg/store/__init__.py
- openghg/store/_meta.py
- openghg/store/base/__init__.py
- openghg/store/base/_base.py
- openghg/store/storage/__init__.py
- openghg/store/storage/_convert.py
- openghg/transform/_transform.py
- openghg/util/__init__.py
- openghg/util/_user.py
* **Summary of changes** 
This adds in some functionality to convert an old style object store to the new Zarr format. This uses some of Brendan's code for the lookup of arguments etc but I've modified it so it just takes everything in an object store and converts it.
It may be a bit temperamental and I've added some log warnings to tell people it's better to just repopulate using the original data. I've also added a short tutorial to cover how to use the new function.
> Add code to convert old store to zarr store

- CHANGELOG.md
- openghg/standardise/_standardise.py
- openghg/store/_boundary_conditions.py
- openghg/store/_eulerian_model.py
- openghg/store/_flux.py
- openghg/store/_footprints.py
- openghg/store/_obscolumn.py
- openghg/store/_obssurface.py
- tests/store/test_boundary_conditions.py
- tests/store/test_eulerian_model.py
- tests/store/test_flux.py
- tests/store/test_footprints.py
- tests/store/test_obscolumn.py
- tests/store/test_obssurface.py
Allowed the standardising functions to accept optional_metadata
Added raise value error if optional_metadata contains keys similar to required_keys
Added tests for both scenarios.
> PR to allow optional metadata dict as tags while standardising data

- openghg/util/_util.py
With current version of the `rapidfuzz` external package (3.9.0) this has started failing the mypy type checking, causing  `openghg.util`to fail the checks. This change updates this to ignore the type coming from this package for now.
Checks not needed:
- ~[Tests added and passed](https://docs.openghg.org/development/python_devel.html#testing) if fixing a bug or adding a new feature~
- ~Added an entry in the latest `CHANGELOG.md` file if fixing a bug or adding a new feature~
> Fix for mypy against latest version of rapidfuzz

- CHANGELOG.md
- openghg/util/_user.py
Previous if a store was empty, the code that checks if it is a zarr store raised an error because no data was found.
This update changes this to log an info item stating that the store is empty and we are treating it as a zarr store.
This fixes a bug that prevented a zarr store from being initialised.
> Empty stores are now treated as zarr stores

- CHANGELOG.md
- doc/source/tutorials/local/Exploring_data/Searching_and_plotting.rst
- openghg/retrieve/_search.py
- tests/retrieve/test_search.py
Updates to search to ensure backwards compatibility with object stores created prior to changes to keywords in PR #968 when retrieving time resolved footprints. Previous PR #968 was to improve the interface by introducing the new, and more accurate, `time_resolved` keyword in favour of `high_time_resolution` but for now we still need to be able retrieve appropriate footprints which are only labelled with `high_time_resolution` and NOT `time_resolved`.
These updates include:
- Update to `openghg.retrieve.search` (actually `_base_search`) to allow dictionary inputs to be passed so that multiple options for keywords can be used (expands on current ability to do this with lists). This performs an OR search with the other keywords. …
> Ensure backwards compatability of new time_resolved key with previous stores

- CHANGELOG.md
- openghg/dataobjects/_basedata.py
- tests/retrieve/conftest.py
- tests/retrieve/test_access.py
If data is added non-sequentially, there is a bug where this cannot be retrieved when passing a time range as the data is not in time order by this point. This PR is a simple fix for this to always sort the data before slicing.
Not needed
> Fix to be able to retrieve non-sequential data

- tests/util/test_user.py
I've noticed files being leftover by the tests using the `tmp_path` fixture. This was due to a `Path` being passed to the mock config instead of a string. This fixes that and moves the other tests in the file to use `tmp_path` instead of `tmppdir` to save some conversion to `Path` throughout the code.
> Move to use tmp_path instead of tmpdir

- CHANGELOG.md
This is additional PR that changes the `ipython` directives from the documentation to `code`.
During the release,-0.8.1 the `ipython` directives failed the execution of deploy to docs.
> Change to documentation `ipython` directives - Release 0.8.1

- CHANGELOG.md
- openghg/store/storage/_localzarrstore.py
- tests/store/storage/test_localzarrstore.py
Added "synchronizer" to `to_zarr` calls to fix race condition, which was causing missing data to appear when standardising multiple files from a loop.
> Iss1031 missing footprint data

- .github/workflows/workflow.yaml
- CHANGELOG.md
- environment-dev.yaml
- environment.yaml
- requirements.txt
Numpy had a major release whle this PR was
in progress. We need to make changes to be
compatible with numpy 2.0.
We also need backwards compatibility with numpy 1.26 for a while because pymc/pytensor hasn't upgraded to numpy 2.0 yet, and openghg_inversions depends on openghg and pymc.
We have also pinned netCDF4 to versions <=1.6.5, since they seem to be having problems moving to numpy 2.0 (and our tests were failing with netCDF4 version 1.7.1).
> Pinned numpy to < 2.0

- CHANGELOG.md
- openghg/analyse/_scenario.py
Two changes to `combine_datasets` in `analyse._scenario`:
1. fixed a typo: "long" changed to "lon"
2. loaded the second (usually smaller) dataset into memory before reindexing. This avoids a weird slow down noticed on inversions. This is documented in [xarray issue #8945](https://github.com/pydata/xarray/issues/8945).
> Fixes for combine datasets (ported from openghg inversions)

- openghg/data/config/objectstore/defaults.json
Small update to defaults.json file to remove repeated "optional" key from the eulerian_model option.
Probably not needed
Not needed:
> Removing repeated 'optional' key from eulerian_model input config file

- openghg/retrieve/_access.py
- tests/retrieve/test_access.py
Added logic from acrg get_gosat code, implemented within the get_obs_function. get_obs_function now retrieves standardised satellite data from a store and processes it to obtain mf_prior_factor, mf_prior_upper_level_factor, mf and mf_repeatability, based on required parameter max_level. If passed max_level is above available max level, it reverts to available max level
> added satellite processing steps to get_obs_column

- CHANGELOG.md
This adds a quick CHANGELOG.md entry for the changes made in PR #1050. This updated the `get_obs_column` function to include previous changes from the acrg repository (see PR details).
> Adding CHANGELOG.md update for PR #1050 on updates to get_obs_column

- .github/workflows/workflow.yaml
Adding a manual trigger for running the tests in the CI through GitHub Actions. When merged into the default branch this should provide an option on the Actions tab to run the tests on command rather than needing a push / PR action to do this.
*Note: it may not be this simple but until this is merged into the default branch we won't be able to check the Actions tab to see if this produces the correct behaviour. At the least though, this should be a small add on and doesn't impact other functionality making it a safe update.*
Not needed:
- ~[Tests added and …
> Add manual CI trigger for tests

- CHANGELOG.md
- tests/store/storage/test_localzarrstore.py
* **Summary of changes** (Bug fix, feature, docs update, ...)**
Updated compressed bytes test to use relative error instead of checking that the compressed bytes exactly equals the expected value.
The number of compressed bytes seems to vary slightly sometimes (possibly due to changes in dependencies).
> Updated compressed bytes test to use rel error

- CHANGELOG.md
- openghg/retrieve/_search.py
- openghg/util/_inlet.py
- tests/retrieve/test_search.py
- "inlet" and "height" now go through "format_inlet", but not "clean_string" when passed to `search`
- modified `format_inlet` to accept a list
> Changed how "inlet" is parsed by search

- CHANGELOG.md
- openghg/store/base/_base.py
Changed how error info is passed via the `BaseStore` context manager. Previously it would just say something like "trace back object at <some address>", now the trace back will be printed.
> Added exc_info= to BaseStore __exit__ method

- CHANGELOG.md
- doc/source/tutorials/local/Adding_data/Adding_observation_data.rst
- openghg/data/config/objectstore/defaults.json
- openghg/retrieve/_search.py
- openghg/standardise/_standardise.py
- openghg/store/_obssurface.py
- tests/retrieve/test_search.py
- tests/store/test_obssurface.py
We want to ensure that obs surface data being added can be distinguished by the source of the data. Within retrieved data (which follows a different path to standardise) there are additional keywords including: `data_source` (e.g. "icos", "ceda") and `dataset_source` ("InGOS", "European ObsPack") which it would be useful to have available more generally.
This PR formalises this to allow `dataset_source` to be specified by the user and `data_source` to be set to "internal" when using the `standardise_surface` interface. These keys are part of the set used to distinguish between different stored Datasources.
*Note: Would like `data_source` to be renamed to `retrieved_from` but kept this the same as ICOS (retrieve_atmospheric) for …
> Tidy up required keys around data_source and dataset_source

- CHANGELOG.md
- openghg/dataobjects/_basedata.py
- openghg/dataobjects/_searchresults.py
- tests/standardise/test_standardise.py
With the recent upgrade of dask to version 2024.8, the chunks returned when retrieving the data from an object store do not match to what we previously expected. This is due to a sort operation which is carried out when all data is retrieved. The sort operation is partially controlled by a `sort` input flag but is performed by default.
The fact that the chunks returned don't exactly match to the stored chunks is not necessarily a problem in itself but it is necessary to test that we are able to add our own custom chunks and this is stored correctly. To fix this test and allow this check to be made the following updates were made:
- Exposed the `sort` keyword when creating BaseData through retrieve interface. This allows the …
> Fix for failing footprint chunk test

- CHANGELOG.md
- openghg/data/config/objectstore/defaults.json
The required keys within the config file should be a mapping onto keys which are used to distinguish datasources within the object store. This is used as part of the data lookup steps when adding new data so we know whether to add data to an existing datasource or to create a new datasource.
This PR removes some additional keywords from the config file which do not need to be used as these distinguishing keys. The keywords removed are:
- `station_long_name` - the `site` code should cover the same purpose and, in general, the same site code should have the same `station_long_name`
- `data_type` - the datasources are already split by `data_type` as part of the structure of the object store so this does not need to be used as a …
> Streamlining keywords within surface required config definition

- CHANGELOG.md
- openghg/data/config/objectstore/defaults.json
- openghg/standardise/_standardise.py
- openghg/store/_obscolumn.py
- tests/store/test_obscolumn.py
Updated required and optional keys for "column" data type (`ObsColumn` data class). This includes all the same keys as previous but rearranged into required and optional definitions to better to match to how we expect this to be used for satellite OR site column data. Also added `platform` as a required key (should be set to "site" or "satellite" though this isn't imposed much at the moment) - this was already a key that could be added through the `standardise_*` framework but was not included within the config.
The defaults.json config now includes:
- required: species, platform [added]
- optional: satellite, selection, domain, site, network
Includes:
- Added in check within `ObsColumn.read_file` for `satellite` OR `site` but …
> Iss1103: Updating required key logic for ObsColumn data class to allow for better flexibility between site/satellite split

- openghg/store/_obssurface.py
- openghg/util/__init__.py
- openghg/util/_time.py
- tests/retrieve/conftest.py
- tests/standardise/test_standardise.py
- tests/store/test_obssurface.py
Move check for sampling_period into the util._time.py module. This is to continue to simplify the checks within `ObsSurface.read_file()` and feeds into PR #1069 to make sure inputs to the read_file function call matches as closely as we can to what is accepted by the `parse` functions. Previously `sampling_period` input was converted to `sampling_period_seconds` which is what was passed to the `parse` functions.
Related to this, sampling_period of "1H" was changed to "1h" as this was causing a warning in the tests.
- Added an entry in the latest `CHANGELOG.md` file if fixing a bug or adding a new feature - small internal change - needed?
Not needed
- ~Documentation and …
> Tidy up: Split out sampling period check

- CHANGELOG.md
- openghg/store/base/_base.py
When storing the file hashes the code was assuming the filepath values were `Path` not `str` type and so was raising an error. This PR updates the `BaseStore.check_hashes` function which creates the file hash details to make sure the filepath (the value in the dictionary) is already a `Path`.
Not needed
> Ensuring filepath values within BaseStore.check_hashes are set to Path type

- CHANGELOG.md
- openghg/standardise/surface/_noaa.py
- tests/standardise/surface/test_noaa.py
Updating keywords to NOAA obspack to ensure these are consistent with current definitions. This includes:
- `data_source` --> `dataset_source`
- Updating keywords which are not set (e.g. sampling_period and potentially other keys) to use central definition for the not_set keyword
This assists with making definitions consistent for PR #1069 .
Not needed
> Tidy up: Update NOAA keywords

- CHANGELOG.md
- openghg/util/_download.py
This is a fix to the two `mypy` errors around the `openghg.util.download_data` function.
The `response.raw.read` method was being patched using `functools.partial` to set the `decode_content` flag to be True but this was unecessary as of [urllib3 PR 159](https://github.com/urllib3/urllib3/pull/159/files) as the `decode_content` flag was now exposed and could be set directly.
This was not fixed, just ignored for now. Justification: this involved the interaction between the `wrap_file` function from the `rich` package and the output from `requests` as these didn't quite align. As these are two third party packages this could easily happen and the "BinaryIO" object expected and the "HTTPResponse | Any" object provided are likely …
> Updating _download.py to fix mypy issues - one fixed and one ignored

- CHANGELOG.md
- openghg/standardise/surface/_noaa.py
- openghg/store/base/_base.py
- openghg/store/spec/__init__.py
- openghg/store/spec/_specification.py
- openghg/util/__init__.py
- openghg/util/_metadata_util.py
- openghg/util/_strings.py
- tests/util/test_metadata_util.py
Splitting out https://github.com/openghg/openghg/pull/1069 to demonstrate the logical steps (Part 3): this is to update the logic for merging additional metadata into the metadata created by the parse functions. This builds on Part 2 https://github.com/openghg/openghg/pull/1112 .
The `BaseStore.update_metadata` method is updated to sure up the logic around combining metadata sources. This also currently includes making sure any mismatches are highlighted.
Three(/four) current sources of metadata are being merged:
- metadata returned from the parse functions / constructed within the data class
- input parameters - live data passed into read_file function - when merging the metadata only the input parameters NOT passed to the …
> Updating and formalising merge logic when combining updating metadata from parse functions

- CHANGELOG.md
- openghg/dataobjects/_datamanager.py
- openghg/store/base/_datasource.py
- openghg/store/storage/_localzarrstore.py
- tests/store/storage/test_localzarrstore.py
Changed `LocalZarrStore.delete_all()` to delete the folder in the `data` dir associated with that zarr store. (That is, to delete `data/<datasource uuid>`, not just `data/<datasource uuid>/zarr`.)
It's possible that this should be handled by the `Datasource` instead. The way `Datasource` and `LocalZarrStore` interact at the moment, the path `data/<datasource uuid>` isn't explicitly used by `Datasource`. Instead, the datasource uuid is passed to `LocalZarrStore`, which decides where it should exist (i.e. in `data/<datasource uuid>/zarr`).
The datasource should probably know where its data is, and tell `LocalZarrStore` where to create the `zarr` directory, but that would be a bigger change. (Also, `LocalZarrStore` handles the …
> Iss1125 empty object store invalid

- openghg/standardise/column/_openghg.py
- openghg/store/_obscolumn.py
Small follow on from PR #1101 to make sure the consistent naming of `filepath` is included for the `ObsColumn` data type class and parse functions as well as for `ObsSurface`. All other classes should already adhere to this.
Not needed:
- Closes #xxxx (Replace xxxx with the Github issue number)
> Tidy up: naming of filepath in ObsColumn

- CHANGELOG.md
- openghg/retrieve/_search.py
- tests/retrieve/test_search.py
It is possible to pass a dictionary to any of the parameters in `search_surface` (or any `search_` functions), so the formatting functions we use must be able to format dictionaries. 
I fixed the specific case of `data_levels`. Formatting done in `_base_search` should work with dictionaries, since this formatting either uses `format_inlet`, which is overloaded to work with dictionaries and lists, or it applies `clean_string`, using cases for lists and dicts.
Note: I had to add a `type: ignore` for the dictionary check because passing a dictionary for `data_level` is not allowed by the signature of `search_surface`. However, this is a problem for all of the arguments in the signature of `search_surface`, so I think we need a …
> search_surface formats dictionary of data levels

- CHANGELOG.md
- openghg/retrieve/_access.py
This PR adds an additional `return_mf` option to `get_obs_column()` to not apply the updates to convert to mf and to just return the original column data (e.g. `xch4`). This is similiar but a bit different to #1130 as this bypasses the steps to convert the data rather than just rename the variables.
This feeds into PR https://github.com/openghg/openghg/pull/1117 (and related to #1130 ) as this allows us to use the `get` functions for both column and site data when creating an expected obspack output.
Not needed
> Adding option to get_obs_column to choose whether to return mole fractions or column values

- CHANGELOG.md
- openghg/standardise/surface/_icos.py
- tests/standardise/surface/test_icos.py
Added inlet_height_magl and data_owner attributes to parse_icos.
A step towards `sync_surface_metadata` movement to store level.
> Added missing attributes to icos and test icos

- CHANGELOG.md
- openghg/store/storage/_localzarrstore.py
With new updates to xarray, it is no longer possible to append data to a zarr store if the chunks of the new data match the chunks of the existing data *and* the existing data in the zarr store has a partial chunk at the point where the new data will start.
To get around this, we can pass `safe_chunks=False` to bypass the new xarray check and keep the existing behavior.
In general, we should avoid this entire problem by adding as much data as possible at once, using
`open_mfdataset` to open the new data files.
There are other ways around this issue besides
setting `safe_chunks=False`, but this would entail detecting partial chunks in the region being written to, and then rechuncking or splitting up the new data so that the …
> Allow ThreadSynchronizer to handle partial chunks

- CHANGELOG.md
- openghg/objectstore/metastore/_classic_metastore.py
- openghg/util/__init__.py
- openghg/util/_file.py
* **Summary of changes** 
If a user does not have the right permissions, an error is raised with a suggested solution.
When the lock is first created, it has rw permissions for user and group.
> Added check for file lock permissions

- CHANGELOG.md
- openghg/store/_boundary_conditions.py
- openghg/store/_eulerian_model.py
The `read_file` method in `EulerianModel` and `BoundaryConditions` had duplicate code and was in a different order from the subclasses of `BaseStore`. This PR fixes that.
> Remove duplicated code from eulerian model

- CHANGELOG.md
- openghg/retrieve/icos/_retrieve.py
- openghg/standardise/meta/__init__.py
- openghg/standardise/meta/_metadata.py
- openghg/store/_obssurface.py
Shifted align_metadata_attributes function declaration from obsurface to metadata.py and called it in retrieve_remote so that update mismatch works for icos remote retrieval.
> Fx1194 sync metadata to retrieve icos

- openghg/objectstore/_config.py
Added exist_ok-True where it creates folderpath. Removed error inside create_default_config
> Metakeys config not found but config folder exists error handling bug

- CHANGELOG.md
- openghg/store/_obssurface.py
- tests/retrieve/icos/test_retrieve_icos.py
The method `ObsSurface.store_data` was still using the old keyword
`icos_data_level` instead of the new keyword `data_level` to distinguish
data sources.
This was causing ICOS data with different levels to be written to the same
datasource.
A test was added to check this; it failed before the change to `store_data`,
and passes afterwards.
> Fix to store ICOS data by data level

- CHANGELOG.md
- openghg/objectstore/_local_store.py
- openghg/objectstore/metastore/_classic_metastore.py
- openghg/store/base/_base.py
- openghg/util/__init__.py
- openghg/util/_file.py
- tests/objectstore/test_file_locks.py
- tests/objectstore/test_local_object_store.py
Changed to make sure `FileLock` object is created with rw-rw-r
permissions.
Changed file lock naming scheme so we'll start fresh with this PR
and won't need to fix the broken permissions on all the old files.
> Fix filelock permissions

- CHANGELOG.md
- openghg/types/_types.py
The function that converts parser outputs to a list
of `MetadataAndData` objects.
* **Please check if the PR fulfils these requirements**
> Allow more types to be returned from parsers

- CHANGELOG.md
- openghg/data_processing/_resampling.py
- tests/data_processing/test_resampling.py
Because `_weighted_resample` creates a new dataset,  to preserve attributes they need to be manually copied to the new dataset. This fixes the issue.
> Fix for missing attributes in weighted resample

- CHANGELOG.md
- doc/source/tutorials/local/Analysing_data/Comparing_with_emissions.rst
- openghg/analyse/_scenario.py
- tests/analyse/test_scenario.py
Within `ModelScenario` this needs to align together observation and footprint data as one of the steps towards created modelled observations. For site (regular) data this is done using resampling methods to ensure the frequency of the observation and footprint data match and that the exact time points are aligned. For flask (irregular) data however, this shouldn't be resampled in the same way as we do not expect this to be on a regular frequency.
This PR is to put in a short term fix where the `platform` keyword can be used to indicate that the footprint data should be aligned to the observations but to not apply any resampling. The check for this looks for `platform` keywords which contain the word "flask" to keep this …
> Adding in filter for 'flask' platform to align but not resample

- CHANGELOG.md
- openghg/standardise/column/_openghg.py
Currently, Zarr complains if there is a difference in dimension size between stored and incoming data. Especially this has been observed for the `exposure_id` variable. As the variable is not that important it is being removed however to avoid such issues to be raised in future for other dimensions please see https://github.com/openghg/openghg/issues/1242
> Dropping of exposure_id variable for GOSAT data containing "exposure_id" variable

- CHANGELOG.md
- openghg/standardise/column/_openghg.py
- tests/standardise/column/test_openghg_column.py
If exposure_id variable is dropped, id coordinate is dropped too. This fixes an issue with standardising and merging obs files (which usually have ID with shape (3,) but in a few files shape is (1,))
> Fixed obs standardisation (issue with ID coordinate)

- CHANGELOG.md
- openghg/store/_footprints.py
- openghg/store/_infer_time.py
- openghg/util/_time.py
- tests/standardise/test_standardise.py
- tests/util/test_time.py
Added relevant warnings, If time_period is varies, the default is set to "1 second".
If continuous=false inferred frequency is set to input_frequency
> 1151 data with period varies cannot be standardised

- CHANGELOG.md
- openghg/objectstore/__init__.py
- openghg/objectstore/_config.py
- tests/objectstore/test_config.py
The keys used for each data_type to distinguish data are defined within a config file. At the moment this config file is copied into an object store when this is first created but this then doesn't get updated if further changes are made to the default.
This PR is to update this workflow:
- Don't create the config file in an object store by default
- Still look for a config file in the object store BUT the filename this looks for has now been changed to "_v2" so the file in old object store will no longer be found and accessed.
- If previous file is detected a warning is included
- If no config file is found this now uses the internal defaults in openghg
- It is still possible to create a config file which will be put in the …
> Update reading of config file to use internal defaults when file is not present in object store

- CHANGELOG.md
- openghg/retrieve/_search.py
Added check to see if start_date and end_date are None then they will be converted to pd.Timestamp format. This results in searching data with start_date and end_date.
start_date = 2016-01-01 14:59:12.500000+00:00
changes to format 2016-01-01 pd.Timestamp(14:59:12.500000+00:00)
> Bug fix timestamp cannot be inferred

- openghg/standardise/_standardise.py
- openghg/standardise/surface/_noaa.py
- tests/store/test_obssurface.py
At the moment `measurement_type` has a default of "insitu" within the `standardise_surface` function. This could cause issues as we're starting to include more data from flask sampling as this means misleading details would be included in the file attributes by default.
Summary of updates:
- Remove default from `standardise_surface` for `measurement_type` and allow this to be None
- Update impacted `parse_noaa` function to check for None input in initial function and make sure this is set to a valid type
- Update impacted tests to make sure `measurement_type` keyword is specified when the `parse_noaa` function will be called.
This also feeds into the work to add the `platform` keyword as an option (see Issue #1247 ) as we'll …
> Removing default from measurement_type in standardise_surface

- openghg/util/_platform.py
Removed optionalPathType and called pathType from openghg.types
> Correction openghg.type import from optionalPathType to pathType and None

- CHANGELOG.md
- openghg/data_processing/_resampling.py
- openghg/retrieve/_access.py
- tests/store/test_obssurface.py
add a keep_variables option in get_obs_surface. This can be use to pr…event resampling functions to try to resample unused variables filled with nans or string
> Fix resampling for surface obs

- openghg/analyse/_alignment.py
Small update to `combine_datasets` function to update steps to use xarray directly rather than using numpy. This is when creating a filter for footprint data to remove infinite values.
From comment on PR #1291 but added as a separate PR since this is a key part of the code.
Not done
- ~Added an entry in the latest `CHANGELOG.md` file if fixing a bug or adding a new feature~
> Update combine_datasets function to use native xarray steps rather than numpy

- CHANGELOG.md
- doc/source/development/python_devel.rst
- environment-dev.yaml
- requirements-dev.txt
- tox.ini
Tests against multiple versions of Python can now
be run locally, emulating our GitHub workflow.
Docs have been added to explain how to do this, but assuming `tox` is installed (via `pip install tox`) and you have Python 3.10, 3.11, and 3.12 installed, then running `tox` in the terminal in your OpenGHG repo will run tests against Python 3.10-3.12, as well as black (check only), flake8, and mypy.
> Added tox for testing

- CHANGELOG.md
- openghg/analyse/_scenario.py
Added option `calc_fp_x_flux` to `ModelScenario.footprints_data_merge`, which adds the fp x flux matrix (which must be calculated to calculate the modelled obs) to the combined data stored in `ModelScenario.scenario` under the data variable name `fp_x_flux`.
This is mostly a neutral change, but the return types of `calc_modelled_obs` and its helper functions have been changed to `xr.Dataset`, and the time series and/or fp_x_flux are returned as data variables in a single dataset. This means that the result of `calc_modelled_obs` can be merged into the combined data, regardless of the options selected.
> Iss1308 option to get fpxflux in footprints data merge

- CHANGELOG.md
- openghg/analyse/_scenario.py
- tests/analyse/test_modelled_obs.py
This option can be passed to `footprints_data_merge`. This will also compute fp_x_flux for each sector, if `calc_fp_x_flux` is True.
The sectoral versions are stored under `mf_mod_sectoral` (or `mf_mod_high_res_sectoral`) and `fp_x_flux_sectoral`.
The total modelled obs (and fp_x_flux) are computed as well.
> Added option to compute modelled obs. (and fp_x_flux) by sector

- CHANGELOG.md
- openghg/retrieve/_access.py
- tests/retrieve/test_access.py
Added units attribute to `mf` of xch4 data var
Added check in the existing test
> Units for mf similar to xch4

- doc/source/tutorials/local/Adding_data/Adding_observation_data.rst
The standardise_surface calls within the documentation are currently using `filepaths` but this was changed in favour of `filepath` in a previous update. This PR is to correct this for the Add_observation_data tutorial.
> Fixing documentation to use `filepath` rather than previous `filepaths`

- openghg/__init__.py
Very small change to help with finding and updating the logging setting in places outside of running openghg directly. This is primarily so we can more easily access the logger and handlers.
The primary use case for this at the moment is to allow us to more easily turn off the logging within the documentation but we may also be able to use this within the tests to stop tests output being written to the log as well.
> Updating the logging to use 'openghg' name directly rather than __name__

- doc/source/conf.py
- doc/source/tutorials/local/Adding_data/Adding_observation_data.rst
- requirements-doc.txt
The Add observation data tutorial currently includes a mix of "code" and "ipython" sphinx directives - some of which run the code and some do not. This update is to include the jupyter-execute directive instead which runs the code and includes a more nicely formatted output for details like pandas DataFrames.
Note for this, the logging level has been raised to ERROR so that INFO and WARNING messages aren't printed within the documentation.
> Update adding observation data tutorial to use jupyter-execute directive

- openghg/store/_obssurface.py
- tests/store/test_obssurface.py
All the data type classes in `openghg.store` use the `check_hashes` and `store_hashes` methods on `BaseStore` except the `ObsSurface` class.
This PR updates the `ObsSurface` class to use these functions. To facilitate this an additional check for a particular source_format (GCWERKS) which looks for tuples of filepaths were rearranged so the filepaths had been extracted by the point the `*hashes` functions were called. A previous, but unusued `store_hashes` method on `ObsSurface` was also removed.
This feeds into #1252 where we're trying to split out the overlapping steps between the different data type classes so this code can be factored out to make this more easy to update going forward.
* **Please check if the PR fulfills …
> Update the ObsSurface read_file function to use the `check_hashes` and `store_hashes` methods

- CHANGELOG.md
- tests/helpers/helpers.py
Added user-based directory in tempfile creation in tests to avoid permission denied error on bluepebble.
> User specific tmp path

- CHANGELOG.md
- openghg/objectstore/_legacy_datasource.py
- openghg/store/storage/_localzarrstore.py
- openghg/store/storage/_store.py
- tests/dataobjects/test_datamanager.py
- tests/store/storage/test_localzarrstore.py
- tests/store/test_datasource.py
Removing unused code will make the `LocalZarrStore` refactor easier. We will also need to refactor `Datasource` in the near future to remove the use of "representative date strings".
Removing unused code or code that is only used in basic tests should make the currently used functionality clearer.
One change didn't involve removing code: the `update` method in `LocalZarrStore` was renamed to `overwrite`, since this matches what the method will be called after the zarr store refactor.
I also flattened some nested "if" statements in `Datasource.add_timed_data`.
Details of code removed that could potentially be used:
- From `Datasource`:
- `get_dataframe_daterange` this was deprecated
- `get_dataset_daterange_str` unused, calls …
> Remove unused code from Datasource and LocalZarrStore

- CHANGELOG.md
- openghg/store/_eulerian_model.py
At the moment the `EulerianModel` data type class doesn't have an associated schema which is used to check parsed data matches to an expected format.
This PR introduces a basic schema which checks that some of the essential coordinates are present and of an appropriate data_type.
Note that we don't have a lot of examples of Eulerian Model data at the moment and are not sure how we're going to want to use it so at the moment so this doesn't include any data variable checks yet but these can be included if we get more examples of different types of data.
Not needed
> Adding a basic schema for EulerianModel

- openghg/analyse/_scenario.py
Typo in for loop in _scenario was calculating total mole fraction contributions and fp_x_flux for all flux sectors rather than individually as intended. 
> Typo for calculating mfs / fluxXfp for multiple sources

- CHANGELOG.md
- openghg/analyse/_modelled_baseline.py
- openghg/analyse/_modelled_obs.py
- openghg/analyse/_scenario.py
- openghg/analyse/_utils.py
- openghg/retrieve/_access.py
- openghg/util/_units.py
- tests/analyse/test_modelled_obs.py
- tests/analyse/test_scenario.py
- tests/analyse/test_utils.py
An option has been added to include BC sensitivities in the result of
`footprints_data_merge`.
This will allow use to compute BC basis functions without having to
duplicate code in OpenGHG inversions.
> Return bc sensitivities from `footprints_data_merge`

- .github/workflows/workflow.yaml
- CHANGELOG.md
- doc/source/tutorials/local/Exploring_data/Retrieving_remote_data.rst
- environment.yaml
- pyproject.toml
- requirements.txt
The authentication steps for icoscp have been updated and this PR is to bring the docs in line with this. This also drops the current pinning of `icoscp` to 0.17.0 within the requirements as this no longer works with the latest authentication method.
Updated to also ensure `numpy>=2.0` as `icoscp` is currently pinned to `numpy<2.0` but our current code seems to work ok with this.
*As long as this works ok for others, this supercedes PR #1139 - here we move to putting the onus on the icoscp docs to tell us how to authenticate rather than needing to maintain an internal authentication method in openghg. If this PR is merged, that PR can be closed.*
Not needed
- …
> Drop pin for icoscp and update authentication details in the docs

- CHANGELOG.md
- openghg/store/_flux.py
- openghg/store/base/_base.py
- openghg/store/storage/__init__.py
- openghg/store/storage/_chunking.py
- tests/retrieve/icos/test_retrieve_icos.py
- tests/store/storage/test_localzarrstore.py
- tests/store/test_flux.py
The `Flux` class now has a "chunking schema". This allows ~time resolved~ flux data to be standardised, regardless of the length of the time coordinate in the raw data.
An option to automatically scale the chunk sizes to fit within the maximum (defaults to 300MB) was added, mostly because some flux tests use the global edgar domain, which is very large.
It would make sense to chunk the lat/lon dimensions of the global edgar domain (or any large domain), but that is somewhat beyond what I wanted to achieve in this bug fix.
----
Not needed
- Documentation updated/added
- Tutorials updated/added
- Wiki updated
-  Added any new requirements to `requirements.txt` and …
> Apply chunking schema to Flux

- CHANGELOG.md
- openghg/retrieve/_access.py
They are converted to NaN before resampling. This only happens if you are resampling the data (I could apply it even if the data isn't resampled, but then the data would need to be loaded into memory.)
- Documentation updated/added
- Tutorials updated/added
- Wiki updated
*Note: if any of the above are not needed for a PR please separate to below and remove the checkbox.*
> Added check for negative uncertainties
